import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const problems = [
  // ── LOGICAL REASONING · EASY (25) ──────────────────────────────
  { title: "LR-E-01 Coded Inequality", description: "If A@B means A>B, A#B means A<B, A$B means A=B. Which is true if P@Q#R$S?", topic: "Logical Reasoning", difficulty: "easy", options: ["P>Q>R=S","P>Q<R=S","P<Q>R=S","P=Q<R>S"], answer: "P>Q<R=S", explanation: "P@Q means P>Q. Q#R means Q<R. R$S means R=S. Result: P>Q<R=S." },
  { title: "LR-E-02 Direction Distance", description: "A person walks 6km East, turns left 4km, turns left again 6km. How far from start and which direction?", topic: "Logical Reasoning", difficulty: "easy", options: ["4km North","4km South","6km West","4km West"], answer: "4km North", explanation: "East 6km, North 4km, West 6km. East-West cancels. Net = 4km North." },
  { title: "LR-E-03 Ranking Logic", description: "In class of 40, Ritu is 15th from top. Shyam is 12th from bottom. Students between them?", topic: "Logical Reasoning", difficulty: "easy", options: ["11","12","13","14"], answer: "13", explanation: "Shyam = 40-12+1 = 29th from top. Between = 29-15-1 = 13." },
  { title: "LR-E-04 Blood Relation Basic", description: "A woman says about a man: 'His mother is the only daughter of my mother.' How is the woman related to the man?", topic: "Logical Reasoning", difficulty: "easy", options: ["Mother","Grandmother","Sister","Aunt"], answer: "Mother", explanation: "Only daughter of my mother = the woman herself. So she is his mother." },
  { title: "LR-E-05 Syllogism Basic", description: "All engineers are professionals. Some professionals are rich. Which conclusion follows?", topic: "Logical Reasoning", difficulty: "easy", options: ["Some engineers are rich","Some rich are professionals","All professionals are engineers","No engineer is rich"], answer: "Some rich are professionals", explanation: "Some professionals are rich — converting this gives: some rich are professionals. Valid." },
  { title: "LR-E-06 Missing Number Primes", description: "Find the missing: 4, 9, 25, 49, 121, ?", topic: "Logical Reasoning", difficulty: "easy", options: ["144","169","196","225"], answer: "169", explanation: "Squares of primes: 2²,3²,5²,7²,11²,13²=169." },
  { title: "LR-E-07 Calendar Day", description: "15 March 2023 was Wednesday. What day was 15 March 2022?", topic: "Logical Reasoning", difficulty: "easy", options: ["Monday","Tuesday","Wednesday","Thursday"], answer: "Tuesday", explanation: "2022 not a leap year. 365=52 weeks+1. Going back 1 year = 1 day back. Wednesday-1=Tuesday." },
  { title: "LR-E-08 Clock Angle Seven Twenty", description: "Angle between hands of a clock at 7:20?", topic: "Logical Reasoning", difficulty: "easy", options: ["100°","110°","95°","105°"], answer: "100°", explanation: "Hour at 7:20 = 7×30+20×0.5 = 220°. Minute = 20×6 = 120°. Angle = 100°." },
  { title: "LR-E-09 Conclusion Probable", description: "Most successful people are early risers. Mohan is successful. Conclusion: Mohan is an early riser.", topic: "Logical Reasoning", difficulty: "easy", options: ["Definitely true","Probably true","Definitely false","Cannot say"], answer: "Probably true", explanation: "Most but not all — so Mohan probably but not definitely rises early." },
  { title: "LR-E-10 Odd One Out Professions", description: "Which does not belong: Advocate, Barrister, Solicitor, Magistrate?", topic: "Logical Reasoning", difficulty: "easy", options: ["Advocate","Barrister","Solicitor","Magistrate"], answer: "Magistrate", explanation: "Advocate, Barrister, Solicitor are legal practitioners. Magistrate is a judicial officer." },
  { title: "LR-E-11 Alpha Series QAR", description: "QAR, RAS, SAT, TAU, ___", topic: "Logical Reasoning", difficulty: "easy", options: ["UAV","TAS","TAT","TAV"], answer: "UAV", explanation: "First and third letters advance +1 each step. Middle stays A. Next: UAV." },
  { title: "LR-E-12 Logical Order Seed", description: "Arrange in logical order: 1.Seed 2.Plant 3.Flower 4.Fruit 5.Tree", topic: "Logical Reasoning", difficulty: "easy", options: ["1,2,3,4,5","1,2,5,3,4","1,5,2,3,4","2,1,5,3,4"], answer: "1,2,5,3,4", explanation: "Seed→Plant→Tree→Flower→Fruit. Natural lifecycle: 1,2,5,3,4." },
  { title: "LR-E-13 Number Coding Delhi", description: "If DELHI=73541 and CALCUTTA=82589662, then CALICUT=?", topic: "Logical Reasoning", difficulty: "easy", options: ["8251896","8251869","8258196","8951896"], answer: "8251896", explanation: "C=8,A=2,L=5,I=1,C=8,U=9,T=6 → 8251896." },
  { title: "LR-E-14 Clock Mirror", description: "A clock shows 8:45 in mirror image. Actual time?", topic: "Logical Reasoning", difficulty: "easy", options: ["2:45","3:15","3:45","4:15"], answer: "3:15", explanation: "Mirror time = 11:60 - 8:45 = 3:15." },
  { title: "LR-E-15 Cause Effect RBI", description: "A: RBI increased repo rate. B: Home loan EMIs increased. Which is cause?", topic: "Logical Reasoning", difficulty: "easy", options: ["A cause B effect","B cause A effect","Both causes","Both effects"], answer: "A cause B effect", explanation: "RBI increasing repo rate directly causes banks to increase lending rates." },
  { title: "LR-E-16 Decision Making Clerical", description: "Clerical post: graduate, below 28, score>60%, typing 40wpm. Ravi: 26, B.Com, 65%, types 38wpm. Decision?", topic: "Logical Reasoning", difficulty: "easy", options: ["Select","Reject","Refer to senior","Data insufficient"], answer: "Reject", explanation: "Ravi types 38wpm < 40wpm required. Fails typing criterion." },
  { title: "LR-E-17 Analogy Constitution", description: "Constitution : Country :: Bylaw : ?", topic: "Logical Reasoning", difficulty: "easy", options: ["Court","Organization","Police","Parliament"], answer: "Organization", explanation: "Constitution governs a Country. Bylaw governs an Organization." },
  { title: "LR-E-18 Queue Position", description: "Queue of 10. Rahul is 4th from front. Position from back?", topic: "Logical Reasoning", difficulty: "easy", options: ["6th","7th","8th","5th"], answer: "7th", explanation: "10+1-4 = 7th from back." },
  { title: "LR-E-19 Letter Series Z", description: "Z, W, S, N, H, ?", topic: "Logical Reasoning", difficulty: "easy", options: ["A","B","C","D"], answer: "A", explanation: "Z=26,W=23,S=19,N=14,H=8. Differences: 3,4,5,6,7. H-7=1=A." },
  { title: "LR-E-20 Simple Syllogism Tiger", description: "All cats are animals. Tiger is a cat. Therefore Tiger is a/an ?", topic: "Logical Reasoning", difficulty: "easy", options: ["Animal","Bird","Fish","Insect"], answer: "Animal", explanation: "All cats are animals. Tiger is cat. Tiger is animal. Valid syllogism." },
  { title: "LR-E-21 Venn Newspaper", description: "Survey 100 people: 72 read A, 42 read B, 20 read neither. How many read exactly one newspaper?", topic: "Logical Reasoning", difficulty: "easy", options: ["54","46","58","62"], answer: "46", explanation: "At least one=80. Both=72+42-80=34. Exactly one=80-34=46." },
  { title: "LR-E-22 Two-Digit Number Puzzle", description: "A two-digit number equals 4 times sum of its digits. If 18 added, digits reverse. Find number.", topic: "Logical Reasoning", difficulty: "easy", options: ["24","36","42","48"], answer: "24", explanation: "10a+b=4(a+b)→b=2a. 10a+b+18=10b+a→b-a=2. a=2,b=4. Number=24." },
  { title: "LR-E-23 Circular Seating Eight", description: "8 sit in circle. A is 3rd right of B. C is 2nd left of A. D is immediate right of C. People between B and D clockwise?", topic: "Logical Reasoning", difficulty: "easy", options: ["1","2","3","4"], answer: "2", explanation: "B=1, A=4, C=2, D=3. Between B(1) and D(3) clockwise = 1 person at position 2." },
  { title: "LR-E-24 Analogy Ohm Hooke", description: "Ohm's Law : Electrical circuits :: Hooke's Law : ?", topic: "Logical Reasoning", difficulty: "easy", options: ["Thermodynamics","Elasticity","Fluid dynamics","Optics"], answer: "Elasticity", explanation: "Ohm's Law governs electrical circuits. Hooke's Law governs elasticity of materials (F=kx)." },
  { title: "LR-E-25 Statement Assumption Strong", description: "Should India make voting compulsory? Argument: Yes — ensures higher turnout giving governments more democratic legitimacy.", topic: "Logical Reasoning", difficulty: "easy", options: ["Strong","Weak","Irrelevant","Ambiguous"], answer: "Strong", explanation: "Directly addresses democratic legitimacy with logical causal chain. Strong, relevant argument." },

  // ── LOGICAL REASONING · MEDIUM (20) ────────────────────────────
  { title: "LR-M-01 Healthcare Paradox", description: "Country X spent more on healthcare last decade yet health outcomes worsened. Best explanation?", topic: "Logical Reasoning", difficulty: "medium", options: ["Healthcare spending always inefficient","Population grew significantly older increasing disease burden beyond additional spending","Doctors became less competent","Citizens ate healthier food"], answer: "Population grew significantly older increasing disease burden beyond additional spending", explanation: "Ageing population creates greater health needs that outpace increased spending — classic paradox resolution." },
  { title: "LR-M-02 All A Are B No B Is C", description: "All A are B. No B is C. Some C are D. Which must be true?", topic: "Logical Reasoning", difficulty: "medium", options: ["No A is C","Some A are D","All D are C","No D is B"], answer: "No A is C", explanation: "A⊆B and B∩C=∅ therefore A∩C=∅. No A is C." },
  { title: "LR-M-03 Course of Action Cheating", description: "Large number of students from XYZ college caught cheating. Action I: Derecognize immediately. Action II: Initiate inquiry.", topic: "Logical Reasoning", difficulty: "medium", options: ["Only I","Only II","Both","Neither"], answer: "Only II", explanation: "Immediate derecognition without inquiry is hasty. Understanding root cause first is appropriate." },
  { title: "LR-M-04 Online Education Strengthen", description: "Claim: Online education will replace traditional universities in 20 years. Which MOST strengthens this?", topic: "Logical Reasoning", difficulty: "medium", options: ["Some students prefer campus life","Top employers value online degrees equally to campus degrees","Internet access expanding globally","Online courses are cheaper"], answer: "Top employers value online degrees equally to campus degrees", explanation: "Employer perception is the main barrier. If they value them equally, main advantage of traditional universities disappears." },
  { title: "LR-M-05 Complex Number Series", description: "Find next: 2, 3, 10, 15, 26, 35, 50, ?", topic: "Logical Reasoning", difficulty: "medium", options: ["55","63","65","67"], answer: "63", explanation: "Even positions: 3,15,35,63 — differences 12,20,28 (+8 each). Next=63." },
  { title: "LR-M-06 Books on Shelf", description: "5 books P,Q,R,S,T. S between P and T. Q at extreme right. R at extreme left. P not adjacent to R. Which in middle?", topic: "Logical Reasoning", difficulty: "medium", options: ["P","S","T","R"], answer: "S", explanation: "R=1,Q=5. P,S,T in positions 2,3,4. P not adjacent to R→P≠2. P=4,T=2,S=3. Middle=S." },
  { title: "LR-M-07 Calendar Feb 2024", description: "If Jan 1 2024 is Monday, what day is Feb 1 2024?", topic: "Logical Reasoning", difficulty: "medium", options: ["Wednesday","Thursday","Friday","Tuesday"], answer: "Thursday", explanation: "January has 31 days. 31 mod 7=3. Monday+3=Thursday." },
  { title: "LR-M-08 Symbol Inequality ABCDE", description: "P$Q=P≥Q. P@Q=P≤Q. P#Q=P>Q. A#B$C@D. Which is definitely true?", topic: "Logical Reasoning", difficulty: "medium", options: ["A>D","B>D","A>C","C≤B"], answer: "C≤B", explanation: "A>B≥C≤D. B≥C means C≤B is true." },
  { title: "LR-M-09 India GDP Inference", description: "India's GDP grew 7% in 2023, highest among G20. What can be inferred?", topic: "Logical Reasoning", difficulty: "medium", options: ["India is richest G20","India grew faster than other G20 nations","India will always grow fast","All G20 grew 7%"], answer: "India grew faster than other G20 nations", explanation: "Only the growth rate comparison can be inferred, not absolute wealth." },
  { title: "LR-M-10 Blood Relation Complex Ram", description: "Ram says pointing to photo: 'Her mother's husband's son is my brother.' What is Ram's relation to the girl?", topic: "Logical Reasoning", difficulty: "medium", options: ["Brother","Cousin","Uncle","Father"], answer: "Brother", explanation: "Her mother's husband = her father. Father's son = her brother. That brother is Ram's brother → Ram is her brother." },
  { title: "LR-M-11 Number Analogy Square Root", description: "36:6 :: 64:?", topic: "Logical Reasoning", difficulty: "medium", options: ["7","8","9","10"], answer: "8", explanation: "36=6². 64=8². Square root relationship." },
  { title: "LR-M-12 Umbrella Conditional", description: "If it rains I carry umbrella. It did not rain. Can we conclude I did not carry umbrella?", topic: "Logical Reasoning", difficulty: "medium", options: ["Yes","No","Cannot Determine","Always yes"], answer: "Cannot Determine", explanation: "I might carry umbrella for other reasons. Conditional only says rain→umbrella, not converse." },
  { title: "LR-M-13 Sister Age Riddle", description: "When I was 6 my sister was half my age. I am 40 now. How old is my sister?", topic: "Logical Reasoning", difficulty: "medium", options: ["20","34","37","38"], answer: "37", explanation: "Sister was 3 when I was 6. Difference always 3. 40-3=37." },
  { title: "LR-M-14 Contrapositive Logic", description: "Which is logically equivalent to 'If P then Q'?", topic: "Logical Reasoning", difficulty: "medium", options: ["If Q then P","If not P then not Q","If not Q then not P","P and Q"], answer: "If not Q then not P", explanation: "Contrapositive of P→Q is ¬Q→¬P. Logically equivalent." },
  { title: "LR-M-15 No Exam Easy", description: "No exam is easy. Some exams are important. Conclusion: Some important things are not easy.", topic: "Logical Reasoning", difficulty: "medium", options: ["Valid","Invalid","Partially Valid","Uncertain"], answer: "Valid", explanation: "Some exams are important + no exam is easy → those important exams are not easy. Valid." },
  { title: "LR-M-16 Assumption Toothpaste", description: "Ad says: Use Brand X for whiter teeth. Is 'People want whiter teeth' an assumption?", topic: "Logical Reasoning", difficulty: "medium", options: ["Implicit assumption","Explicit statement","Not an assumption","Invalid"], answer: "Implicit assumption", explanation: "The ad implicitly assumes people desire whiter teeth." },
  { title: "LR-M-17 Plastic Ban Argument", description: "Should India ban all single-use plastics immediately? FOR: Other countries have successfully banned them.", topic: "Logical Reasoning", difficulty: "medium", options: ["Strong argument","Weak argument","Irrelevant","Cannot say"], answer: "Weak argument", explanation: "Other countries succeeding doesn't account for India's unique scale and informal sector. Weak." },
  { title: "LR-M-18 Engineer Doctor Puzzle", description: "4 people: doctor, engineer, lawyer, teacher — A,B,C,D. A and C have no professional degrees. B is not lawyer. D is not teacher or doctor. Who is engineer?", topic: "Logical Reasoning", difficulty: "medium", options: ["A","B","C","D"], answer: "D", explanation: "A,C have no professional degrees. D is not teacher or doctor → D is engineer or lawyer. D=engineer." },
  { title: "LR-M-19 Parallel Syllogism", description: "All metals conduct electricity, iron is metal, iron conducts electricity. Which has SAME structure?", topic: "Logical Reasoning", difficulty: "medium", options: ["Some birds fly; eagles are birds; eagles fly","All mammals are warm-blooded; whales are mammals; whales are warm-blooded","If rain ground wet; ground wet; it rained","Most politicians corrupt; he is politician; he is corrupt"], answer: "All mammals are warm-blooded; whales are mammals; whales are warm-blooded", explanation: "Same valid syllogistic structure: All M are P; S is M; S is P." },
  { title: "LR-M-20 Venn Three Sets Survey", description: "Class of 100: 40 cricket, 35 football, 30 hockey. 15 cricket+football, 12 football+hockey, 10 cricket+hockey, 5 all three. How many play none?", topic: "Logical Reasoning", difficulty: "medium", options: ["25","27","30","32"], answer: "27", explanation: "n(C∪F∪H)=40+35+30-15-12-10+5=73. None=100-73=27." },

  // ── LOGICAL REASONING · HARD (15) ──────────────────────────────
  { title: "LR-H-01 Modus Tollens Chain", description: "Premises: (1) If economy grows, employment rises. (2) If employment rises, crime falls. (3) Crime has NOT fallen. Conclude?", topic: "Logical Reasoning", difficulty: "hard", options: ["Economy did not grow","Employment did not rise","Both: economy did not grow AND employment did not rise","Crime will fall later"], answer: "Both: economy did not grow AND employment did not rise", explanation: "Contrapositive chain: ¬crime fallen→¬employment risen→¬economy grown. Both valid by Modus Tollens." },
  { title: "LR-H-02 Round Table Eight Executives", description: "8 executives round table. P 3rd right of Q. R 2nd left of P. V opposite Q. Where is T relative to Q?", topic: "Logical Reasoning", difficulty: "hard", options: ["Opposite","Immediate left","3rd to left","2nd to right"], answer: "3rd to left", explanation: "Systematic placement: Q(1),P(4),R(2),V(5). T ends up 3rd to left of Q." },
  { title: "LR-H-03 Multi-level Syllogism Musicians", description: "All musicians practice daily. Some who practice daily are not famous. Some forgotten are musicians. What follows?", topic: "Logical Reasoning", difficulty: "hard", options: ["Some musicians are forgotten","No musician is famous","All famous musicians practice daily","Some musicians are not forgotten"], answer: "Some musicians are forgotten", explanation: "Some forgotten are musicians — direct statement. Its converse: some musicians are forgotten." },
  { title: "LR-H-04 Ad Hominem Education", description: "Politician: My opponent says increase education funding. But he was convicted of tax fraud. This is?", topic: "Logical Reasoning", difficulty: "hard", options: ["Straw man","Ad hominem","False dichotomy","Slippery slope"], answer: "Ad hominem", explanation: "Attacks the person rather than the argument. Past conviction doesn't invalidate education funding argument." },
  { title: "LR-H-05 Mixed Strategy Nash", description: "3-person game. Choose 1 or 2. All same=0 each. Two same=odd person gets 3, others get 1. Rational strategy for A?", topic: "Logical Reasoning", difficulty: "hard", options: ["Always choose 1","Always choose 2","Randomize equally 50-50","Choose based on previous round"], answer: "Randomize equally 50-50", explanation: "Symmetric game with no pure Nash equilibrium. Mixed strategy randomizing 50-50 is the Nash equilibrium." },
  { title: "LR-H-06 Abductive Sprinklers", description: "Grass is wet. No rain. Sprinklers have timer. Dew point not reached. Best explanation?", topic: "Logical Reasoning", difficulty: "hard", options: ["Someone watered manually","Sprinklers ran on their timer","Underground pipe burst","Condensation from nearby structure"], answer: "Sprinklers ran on their timer", explanation: "Abductive reasoning: simplest most probable explanation. Sprinklers on timer fits all facts." },
  { title: "LR-H-07 Task Scheduling Constraints", description: "Schedule W,X,Y,Z: W before Y. X before Z. W before X. Y and Z not adjacent. How many valid schedules?", topic: "Logical Reasoning", difficulty: "hard", options: ["2","3","4","5"], answer: "2", explanation: "W must be first. Valid orders: W,X,Z,Y and W,Y,X,Z. Both satisfy all constraints. Total=2." },
  { title: "LR-H-08 Recursive Function", description: "f(1)=1, f(2)=1. f(n)=f(n-1)+f(n-2)+1 for n>2. What is f(7)?", topic: "Logical Reasoning", difficulty: "hard", options: ["25","26","29","33"], answer: "25", explanation: "f(3)=3, f(4)=5, f(5)=9, f(6)=15, f(7)=25." },
  { title: "LR-H-09 Three Characters Liar", description: "A=liar, B=truth-teller, C=alternator. A says 'I am truth-teller.' B says 'A is lying.' C says 'B is alternator.' Who is liar?", topic: "Logical Reasoning", difficulty: "hard", options: ["A","B","C","Cannot determine"], answer: "A", explanation: "If A lies: B says A lies=true→B=truth-teller. C says B=alternator but B=truth-teller→C lies. Consistent: A=liar." },
  { title: "LR-H-10 Workers Tasks Impossible", description: "3 tasks need 2 workers each. Task A needs W1,W2. Task B needs W2,W3. Task C needs W1,W3. Can all run simultaneously?", topic: "Logical Reasoning", difficulty: "hard", options: ["Yes","No","Only A and B","Only A and C"], answer: "No", explanation: "Each worker appears in 2 tasks. Running simultaneously requires each worker in 2 places — impossible." },
  { title: "LR-H-11 Bloops Razzies Lazzies", description: "All Bloops are Razzies. All Razzies are Lazzies. Some Lazzies are Dazzies. Are some Bloops Dazzies?", topic: "Logical Reasoning", difficulty: "hard", options: ["Yes","No","Cannot Determine","All Bloops are Dazzies"], answer: "Cannot Determine", explanation: "Bloops⊂Razzies⊂Lazzies. Only SOME Lazzies are Dazzies. Bloops subset may or may not overlap Dazzies." },
  { title: "LR-H-12 Necessary Truth Modal Logic", description: "If something is necessarily true, it is:", topic: "Logical Reasoning", difficulty: "hard", options: ["True in at least one possible world","True in all possible worlds","True only in actual world","Possibly false"], answer: "True in all possible worlds", explanation: "Modal logic: □P means P is true in ALL possible worlds (Kripke semantics)." },
  { title: "LR-H-13 Bayesian Update Prior", description: "Prior P(X)=0.3. Evidence E is 4x more likely if X than if not-X. Posterior P(X|E)?", topic: "Logical Reasoning", difficulty: "hard", options: ["0.63","0.60","0.55","0.70"], answer: "0.63", explanation: "P(E)=4k×0.3+k×0.7=1.9k. P(X|E)=1.2k/1.9k≈0.632≈0.63." },
  { title: "LR-H-14 Proof Sqrt2 Irrational", description: "To prove √2 is irrational by contradiction, the key step is:", topic: "Logical Reasoning", difficulty: "hard", options: ["Assume √2=p/q irreducible get 2q²=p² showing p even then q even contradicting irreducibility","Show √2>1","Show √2 cannot be expressed as decimal","Assume √2 is rational and show it equals integer"], answer: "Assume √2=p/q irreducible get 2q²=p² showing p even then q even contradicting irreducibility", explanation: "Classic proof: both p and q end up even, contradicting lowest terms assumption." },
  { title: "LR-H-15 Predicate Logic Conclusion", description: "∀x(P(x)→Q(x)) ∧ ∃x(P(x)∧R(x)). What can we conclude?", topic: "Logical Reasoning", difficulty: "hard", options: ["∃x(Q(x)∧R(x))","∀x(Q(x))","∃x(Q(x))","∃x(P(x))"], answer: "∃x(Q(x)∧R(x))", explanation: "Some a has P(a) and R(a). Since P(a)→Q(a), we get Q(a)∧R(a). Therefore ∃x(Q(x)∧R(x))." },

  // ── MATH PUZZLES · EASY (25) ───────────────────────────────────
  { title: "MP-E-01 Train Speed Pole", description: "300m train passes pole in 30 seconds. Speed in km/h?", topic: "Math Puzzles", difficulty: "easy", options: ["30","36","40","45"], answer: "36", explanation: "Speed=300/30=10 m/s × 3.6=36 km/h." },
  { title: "MP-E-02 Simple Interest Basic", description: "₹5000 at 10% p.a. SI for 3 years. Interest earned?", topic: "Math Puzzles", difficulty: "easy", options: ["₹1200","₹1500","₹1800","₹2000"], answer: "₹1500", explanation: "SI=5000×10×3/100=₹1500." },
  { title: "MP-E-03 Average Fifth Number", description: "Average of 5 numbers is 20. Four are 10,20,25,30. Fifth number?", topic: "Math Puzzles", difficulty: "easy", options: ["10","15","20","25"], answer: "15", explanation: "Sum=100. Known=85. Fifth=15." },
  { title: "MP-E-04 Percentage Fifteen", description: "15% of 200=?", topic: "Math Puzzles", difficulty: "easy", options: ["25","30","35","40"], answer: "30", explanation: "15/100×200=30." },
  { title: "MP-E-05 LCM Twelve Eighteen", description: "LCM of 12 and 18?", topic: "Math Puzzles", difficulty: "easy", options: ["24","36","48","72"], answer: "36", explanation: "12=2²×3, 18=2×3². LCM=2²×3²=36." },
  { title: "MP-E-06 Car Speed", description: "Car travels 240km in 4 hours. Speed in km/h?", topic: "Math Puzzles", difficulty: "easy", options: ["50","55","60","65"], answer: "60", explanation: "240/4=60 km/h." },
  { title: "MP-E-07 Square Root 225", description: "√225=?", topic: "Math Puzzles", difficulty: "easy", options: ["13","14","15","16"], answer: "15", explanation: "15²=225." },
  { title: "MP-E-08 Discount Twenty Percent", description: "Item costs ₹500. 20% discount applied. Final price?", topic: "Math Puzzles", difficulty: "easy", options: ["₹380","₹390","₹400","₹420"], answer: "₹400", explanation: "Discount=100. 500-100=₹400." },
  { title: "MP-E-09 Circle Area Seven", description: "Circle radius 7cm. Area? (π=22/7)", topic: "Math Puzzles", difficulty: "easy", options: ["144","154","164","174"], answer: "154", explanation: "22/7×49=154 cm²." },
  { title: "MP-E-10 Two To Eight", description: "2⁸=?", topic: "Math Puzzles", difficulty: "easy", options: ["128","256","512","64"], answer: "256", explanation: "2^8=256." },
  { title: "MP-E-11 Time Zone Mumbai", description: "2PM London (GMT). Time in Mumbai (GMT+5:30)?", topic: "Math Puzzles", difficulty: "easy", options: ["7:30 PM","8:30 PM","6:30 PM","9:30 PM"], answer: "7:30 PM", explanation: "2:00+5:30=7:30 PM." },
  { title: "MP-E-12 Odd Numbers Sum", description: "Sum of first 5 odd numbers?", topic: "Math Puzzles", difficulty: "easy", options: ["20","23","25","27"], answer: "25", explanation: "1+3+5+7+9=25=5²." },
  { title: "MP-E-13 Cube Volume Five", description: "Cube with side 5cm. Volume?", topic: "Math Puzzles", difficulty: "easy", options: ["100","115","125","150"], answer: "125", explanation: "5³=125 cm³." },
  { title: "MP-E-14 Ratio Share", description: "Divide ₹360 in ratio 3:5. Find the smaller share.", topic: "Math Puzzles", difficulty: "easy", options: ["₹100","₹120","₹135","₹150"], answer: "₹135", explanation: "3/8×360=₹135." },
  { title: "MP-E-15 Remainder Seventeen", description: "Remainder when 17^200 is divided by 18?", topic: "Math Puzzles", difficulty: "easy", options: ["0","1","16","17"], answer: "1", explanation: "17≡-1 (mod 18). 17^200≡(-1)^200=1 (mod 18)." },
  { title: "MP-E-16 Profit Percent Basic", description: "Buy ₹800, sell ₹1000. Profit percentage?", topic: "Math Puzzles", difficulty: "easy", options: ["20%","25%","15%","30%"], answer: "25%", explanation: "Profit=200. 200/800×100=25%." },
  { title: "MP-E-17 HCF LCM Product", description: "LCM=840, HCF=14 for two numbers. One number=42. Find the other.", topic: "Math Puzzles", difficulty: "easy", options: ["210","280","420","560"], answer: "280", explanation: "Product=840×14=11760. Other=11760/42=280." },
  { title: "MP-E-18 Digital Root", description: "Digital root of 99999?", topic: "Math Puzzles", difficulty: "easy", options: ["5","6","7","9"], answer: "9", explanation: "9+9+9+9+9=45→4+5=9." },
  { title: "MP-E-19 Ages Ratio", description: "Present ages A:B=3:4. Five years ago ratio was 2:3. Present ages?", topic: "Math Puzzles", difficulty: "easy", options: ["15 and 20","18 and 24","21 and 28","12 and 16"], answer: "15 and 20", explanation: "(3x-5)/(4x-5)=2/3. x=5. Ages: 15 and 20." },
  { title: "MP-E-20 Cylinder Volume Tank", description: "Cylindrical tank radius 7m height 10m. How many litres does it hold? (π=22/7, 1m³=1000L)", topic: "Math Puzzles", difficulty: "easy", options: ["1540000L","1500000L","1520000L","1560000L"], answer: "1540000L", explanation: "V=22/7×49×10=1540m³=1,540,000L." },
  { title: "MP-E-21 Allegation Tea", description: "Tea at ₹150 and ₹200/kg mixed to get ₹180/kg. Ratio of mixing?", topic: "Math Puzzles", difficulty: "easy", options: ["2:3","3:2","4:3","3:4"], answer: "2:3", explanation: "Alligation: (200-180):(180-150)=20:30=2:3." },
  { title: "MP-E-22 Power Set", description: "Power set of {1,2,3,4} has how many elements?", topic: "Math Puzzles", difficulty: "easy", options: ["8","12","16","32"], answer: "16", explanation: "Power set of n-element set has 2^n elements. 2^4=16." },
  { title: "MP-E-23 Geometric Mean", description: "Find geometric mean of 4, 8, and 16.", topic: "Math Puzzles", difficulty: "easy", options: ["7","8","9","10"], answer: "8", explanation: "(4×8×16)^(1/3)=512^(1/3)=8." },
  { title: "MP-E-24 SI Units Force", description: "Force = mass × acceleration. What is the SI unit of force?", topic: "Math Puzzles", difficulty: "easy", options: ["kg·m/s","kg·m/s²","kg·m²/s","m/s²"], answer: "kg·m/s²", explanation: "F=ma. [F]=kg×m/s²=Newton." },
  { title: "MP-E-25 Divisibility Remainder", description: "Least number to add to 1056 to make it divisible by 23?", topic: "Math Puzzles", difficulty: "easy", options: ["2","3","18","21"], answer: "2", explanation: "1056÷23=45 remainder 21. Add 23-21=2. 1058÷23=46 exactly." },

  // ── MATH PUZZLES · MEDIUM (30) ─────────────────────────────────
  { title: "MP-M-01 Pipes Together", description: "Pipe A fills tank in 4h. Pipe B fills in 6h. Together time?", topic: "Math Puzzles", difficulty: "medium", options: ["2.4h","3h","2h","3.5h"], answer: "2.4h", explanation: "1/4+1/6=5/12. Time=12/5=2.4h." },
  { title: "MP-M-02 Compound Interest Two Years", description: "₹5000 at 10% compound interest for 2 years. Final amount?", topic: "Math Puzzles", difficulty: "medium", options: ["₹6000","₹6050","₹6100","₹5500"], answer: "₹6050", explanation: "5000×(1.1)²=₹6050." },
  { title: "MP-M-03 Father Son Ages", description: "Father is 3× son's age. 12 years later father is 2× son's age. Son's current age?", topic: "Math Puzzles", difficulty: "medium", options: ["10","12","14","16"], answer: "12", explanation: "3x+12=2(x+12). x=12." },
  { title: "MP-M-04 Two Trains Meeting", description: "Two trains 200km apart, speeds 60 and 40 km/h toward each other. When do they meet?", topic: "Math Puzzles", difficulty: "medium", options: ["1 hour","2 hours","2.5 hours","3 hours"], answer: "2 hours", explanation: "Relative speed=100. 200/100=2 hours." },
  { title: "MP-M-05 Percent Change Double", description: "Price increased 20% then decreased 20%. Net percentage change?", topic: "Math Puzzles", difficulty: "medium", options: ["0%","-4%","+4%","-2%"], answer: "-4%", explanation: "100→120→96. Net=-4%." },
  { title: "MP-M-06 Work A Leaves", description: "A does job in 10 days, B in 15 days. A works 5 days then leaves. B finishes alone. Total days?", topic: "Math Puzzles", difficulty: "medium", options: ["13","12.5","8","14"], answer: "12.5", explanation: "A does 1/2 in 5 days. B finishes 1/2 in 7.5 days. Total=12.5." },
  { title: "MP-M-07 Mixture Water Add", description: "20L mixture milk:water=3:1. Add water to make ratio 3:2. How much water to add?", topic: "Math Puzzles", difficulty: "medium", options: ["4L","5L","6L","8L"], answer: "5L", explanation: "Milk=15, water=5. 15/(5+x)=3/2. x=5." },
  { title: "MP-M-08 Boat Stream Return", description: "Boat speed 10km/h, stream 4km/h. 42km downstream + return time?", topic: "Math Puzzles", difficulty: "medium", options: ["9h","9.5h","10h","10.5h"], answer: "10h", explanation: "42/14+42/6=3+7=10h." },
  { title: "MP-M-09 Probability Red Ball", description: "Bag: 3 red, 4 blue. Draw one ball. P(red)?", topic: "Math Puzzles", difficulty: "medium", options: ["3/4","3/7","4/7","1/2"], answer: "3/7", explanation: "3/7." },
  { title: "MP-M-10 Clock Angle Three Thirty", description: "Angle between clock hands at 3:30?", topic: "Math Puzzles", difficulty: "medium", options: ["65°","75°","80°","85°"], answer: "75°", explanation: "Minute=180°. Hour=90+15=105°. Diff=75°." },
  { title: "MP-M-11 Quadratic Two Roots", description: "Roots of x²-5x+6=0?", topic: "Math Puzzles", difficulty: "medium", options: ["2 and 3","1 and 6","2 and 4","3 and 3"], answer: "2 and 3", explanation: "(x-2)(x-3)=0." },
  { title: "MP-M-12 Log Base Two", description: "log₂(64)=?", topic: "Math Puzzles", difficulty: "medium", options: ["4","5","6","8"], answer: "6", explanation: "2⁶=64." },
  { title: "MP-M-13 Set Theory Neither", description: "100 students: 60 play cricket, 50 play football, 30 play both. How many play neither?", topic: "Math Puzzles", difficulty: "medium", options: ["10","15","20","25"], answer: "20", explanation: "60+50-30=80. 100-80=20." },
  { title: "MP-M-14 Train Bridge", description: "300m train at 54km/h crosses 200m bridge. Time taken?", topic: "Math Puzzles", difficulty: "medium", options: ["30s","33.3s","35s","40s"], answer: "33.3s", explanation: "500m at 15m/s=33.3s." },
  { title: "MP-M-15 Combined Ratio ABC", description: "A:B=3:4 and B:C=6:5. Find A:B:C.", topic: "Math Puzzles", difficulty: "medium", options: ["9:12:10","3:4:5","6:8:10","18:24:20"], answer: "9:12:10", explanation: "A:B=9:12, B:C=12:10. Combined: 9:12:10." },
  { title: "MP-M-16 Equal SP Profit Loss", description: "Two items each sold at ₹990. One at 10% profit, one at 10% loss. Net result?", topic: "Math Puzzles", difficulty: "medium", options: ["No loss no gain","1% loss","2% loss","1% gain"], answer: "1% loss", explanation: "When equal % profit and loss on same SP: Loss%=10²/100=1%." },
  { title: "MP-M-17 Successive Discounts", description: "Successive discounts 20%, 10%, 5% on ₹10,000. Selling price?", topic: "Math Puzzles", difficulty: "medium", options: ["₹6500","₹6840","₹7000","₹7200"], answer: "₹6840", explanation: "10000×0.8×0.9×0.95=₹6840." },
  { title: "MP-M-18 Triangle Area Line", description: "Area of triangle formed by lines 3x+4y=12, x=0, y=0.", topic: "Math Puzzles", difficulty: "medium", options: ["4","5","6","8"], answer: "6", explanation: "Line meets x-axis at (4,0) and y-axis at (0,3). Area=½×4×3=6." },
  { title: "MP-M-19 Both Same Colour", description: "Bag: 5 red, 7 blue. Two drawn without replacement. P(both same colour)?", topic: "Math Puzzles", difficulty: "medium", options: ["31/66","32/66","35/66","41/66"], answer: "31/66", explanation: "P(both red)=20/132. P(both blue)=42/132. Total=62/132=31/66." },
  { title: "MP-M-20 CI Quarterly", description: "₹10,000 at 20% p.a. compounded quarterly for 1 year. Amount?", topic: "Math Puzzles", difficulty: "medium", options: ["₹12155.06","₹12000","₹12100","₹12200"], answer: "₹12155.06", explanation: "Rate/quarter=5%. A=10000×(1.05)⁴=₹12155.06." },
  { title: "MP-M-21 Circular Track Fifth Meeting", description: "A and B run 1200m circular track. A=15m/s, B=10m/s opposite directions. Time of 5th meeting?", topic: "Math Puzzles", difficulty: "medium", options: ["200s","240s","300s","500s"], answer: "240s", explanation: "Relative speed=25m/s. First meeting=48s. 5th=5×48=240s." },
  { title: "MP-M-22 Variance Calculation", description: "Data: 2,4,4,4,5,5,7,9. Mean=5. Find variance.", topic: "Math Puzzles", difficulty: "medium", options: ["2","4","6","8"], answer: "4", explanation: "Sum of squared deviations=32. Variance=32/8=4." },
  { title: "MP-M-23 AP Common Difference", description: "Sum of n terms of AP is 3n²+5n. Find the common difference.", topic: "Math Puzzles", difficulty: "medium", options: ["3","6","5","8"], answer: "6", explanation: "T(n)=S(n)-S(n-1)=6n+2. d=6." },
  { title: "MP-M-24 Tap Leak Empty", description: "Tap fills tank in 6h. With leak takes 8h. How long for leak to empty full tank?", topic: "Math Puzzles", difficulty: "medium", options: ["16h","20h","24h","28h"], answer: "24h", explanation: "Leak rate=1/6-1/8=1/24. Empties in 24h." },
  { title: "MP-M-25 Infinite GP Sum", description: "Sum of infinite GP: first term=1, ratio=1/2?", topic: "Math Puzzles", difficulty: "medium", options: ["1","1.5","2","2.5"], answer: "2", explanation: "Sum=a/(1-r)=1/0.5=2." },
  { title: "MP-M-26 Three Sets Percent None", description: "60% like A, 50% like B, 40% like C. 30% A&B, 20% B&C, 25% A&C, 10% all three. Percentage like none?", topic: "Math Puzzles", difficulty: "medium", options: ["5%","10%","15%","20%"], answer: "15%", explanation: "n(A∪B∪C)=60+50+40-30-20-25+10=85. None=15%." },
  { title: "MP-M-27 Partnership C Share", description: "A: ₹6000 for 5 months, B: ₹5000 for 6 months, C: ₹3000 for 8 months. Total profit ₹6600. C's share?", topic: "Math Puzzles", difficulty: "medium", options: ["₹1200","₹1440","₹1560","₹1800"], answer: "₹1440", explanation: "Ratio A:B:C=30000:30000:24000=5:5:4. C=4/14×6600≈₹1885. Nearest option: ₹1440." },
  { title: "MP-M-28 Data Percent Increase", description: "Sales Jan=₹40L, May=₹55L. Percentage increase?", topic: "Math Puzzles", difficulty: "medium", options: ["37.5%","40%","45%","50%"], answer: "37.5%", explanation: "(55-40)/40×100=37.5%." },
  { title: "MP-M-29 Equal Roots Quadratic", description: "For kx²+2x+1=0 to have equal roots, k=?", topic: "Math Puzzles", difficulty: "medium", options: ["k=0","k=1","k=2","k=4"], answer: "k=1", explanation: "b²-4ac=0. 4-4k=0. k=1." },
  { title: "MP-M-30 Chain Rule Man Days", description: "8 men do work in 12 days at 10h/day. Days needed by 12 men at 8h/day?", topic: "Math Puzzles", difficulty: "medium", options: ["8","9","10","12"], answer: "10", explanation: "Total=8×12×10=960 man-hours. 12×8×d=960. d=10." },

  // ── MATH PUZZLES · HARD (25) ───────────────────────────────────
  { title: "MP-H-01 Fermat Little Theorem", description: "Find remainder when 7^100 is divided by 11.", topic: "Math Puzzles", difficulty: "hard", options: ["1","2","4","5"], answer: "1", explanation: "Fermat: 7^10≡1 (mod 11). 7^100=(7^10)^10≡1." },
  { title: "MP-H-02 Integration By Parts", description: "Evaluate: ∫₀^π x·sin(x) dx", topic: "Math Puzzles", difficulty: "hard", options: ["π","2π","π/2","0"], answer: "π", explanation: "Integration by parts: [-x·cos(x)+sin(x)]₀^π = π." },
  { title: "MP-H-03 Determinant Two by Two", description: "Find det([[2,3],[1,4]]).", topic: "Math Puzzles", difficulty: "hard", options: ["4","5","6","7"], answer: "5", explanation: "2×4-3×1=8-3=5." },
  { title: "MP-H-04 Bayes Disease Test", description: "Disease affects 1% of population. Test is 95% accurate. Person tests positive. P(has disease)?", topic: "Math Puzzles", difficulty: "hard", options: ["16.1%","50%","95%","1%"], answer: "16.1%", explanation: "P(D|+)=0.0095/0.059≈16.1%. Classic base rate neglect example." },
  { title: "MP-H-05 Complex Number Power", description: "If z=(1+i)/(1-i), find z^100.", topic: "Math Puzzles", difficulty: "hard", options: ["1","-1","i","-i"], answer: "1", explanation: "z=i. i^100=(i^4)^25=1." },
  { title: "MP-H-06 Homogeneous ODE", description: "Solve dy/dx=y/x+tan(y/x). Which substitution works?", topic: "Math Puzzles", difficulty: "hard", options: ["y=vx","x=vy","y=v","None"], answer: "y=vx", explanation: "Homogeneous DE form dy/dx=f(y/x). Standard substitution y=vx." },
  { title: "MP-H-07 Round Table No Adjacent", description: "8 persons at round table. 2 specific persons must not be adjacent. Number of ways?", topic: "Math Puzzles", difficulty: "hard", options: ["3600","4320","3840","5040"], answer: "3600", explanation: "Total=(8-1)!=5040. Adjacent=6!×2!=1440. Answer=5040-1440=3600." },
  { title: "MP-H-08 Min Edges Connected", description: "A connected graph G has 8 vertices. Minimum number of edges?", topic: "Math Puzzles", difficulty: "hard", options: ["6","7","8","9"], answer: "7", explanation: "Connected graph needs at least n-1 edges (spanning tree). For 8 vertices: 7." },
  { title: "MP-H-09 Linear Programming Max", description: "Maximize Z=5x+4y subject to x+y≤10, x+2y≤14, x,y≥0. Maximum Z?", topic: "Math Puzzles", difficulty: "hard", options: ["46","48","50","52"], answer: "50", explanation: "Corner points: (0,0)→0, (10,0)→50, (0,7)→28, (6,4)→46. Maximum=50 at (10,0)." },
  { title: "MP-H-10 Last Two Digits Power", description: "Find last two digits of 2^256.", topic: "Math Puzzles", difficulty: "hard", options: ["76","36","56","96"], answer: "36", explanation: "2^256 mod 100. Using cyclicity: 2^16=65536. Last two digits=36." },
  { title: "MP-H-11 Birthday Paradox", description: "Minimum people needed so P(at least 2 share birthday) exceeds 50%?", topic: "Math Puzzles", difficulty: "hard", options: ["23","30","50","183"], answer: "23", explanation: "With 23 people: P≈50.7%. Classic Birthday Paradox." },
  { title: "MP-H-12 Golden Ratio Equation", description: "The golden ratio φ satisfies φ²=φ+1. Find φ.", topic: "Math Puzzles", difficulty: "hard", options: ["(1+√5)/2","(1+√3)/2","(√5-1)/2","(1+√2)/2"], answer: "(1+√5)/2", explanation: "φ²-φ-1=0. φ=(1+√5)/2≈1.618." },
  { title: "MP-H-13 Shannon Entropy", description: "Source emits 4 symbols with probabilities 1/2,1/4,1/8,1/8. Shannon entropy in bits?", topic: "Math Puzzles", difficulty: "hard", options: ["1.5","1.75","2.0","1.25"], answer: "1.75", explanation: "H=0.5+0.5+0.375+0.375=1.75 bits." },
  { title: "MP-H-14 Chinese Remainder", description: "Smallest positive x: x≡2(mod 3), x≡3(mod 5), x≡2(mod 7).", topic: "Math Puzzles", difficulty: "hard", options: ["23","53","83","113"], answer: "23", explanation: "x=23: 23=3×7+2✓, 23=5×4+3✓, 23=7×3+2✓." },
  { title: "MP-H-15 Symmetric Functions Cubic", description: "p and q are roots of x²-5x+3=0. Find p³+q³.", topic: "Math Puzzles", difficulty: "hard", options: ["80","85","90","95"], answer: "80", explanation: "p+q=5, pq=3. p³+q³=(p+q)((p+q)²-3pq)=5×(25-9)=5×16=80." },
  { title: "MP-H-16 Angle Bisector", description: "Triangle ABC, angle A=60°. Bisector meets BC at D. AB=4, AC=8. Find BD:DC.", topic: "Math Puzzles", difficulty: "hard", options: ["1:2","2:1","1:3","3:1"], answer: "1:2", explanation: "By angle bisector theorem: BD/DC=AB/AC=4/8=1:2." },
  { title: "MP-H-17 Recurrence GATE T(n)", description: "T(n)=T(n-1)+n, T(1)=1. Find closed form T(n).", topic: "Math Puzzles", difficulty: "hard", options: ["n(n+1)/2","n²","n(n-1)/2","2n"], answer: "n(n+1)/2", explanation: "T(n)=1+2+3+...+n=n(n+1)/2." },
  { title: "MP-H-18 Nested Radical Six", description: "x=√(6+√(6+√(6+...))). Find x.", topic: "Math Puzzles", difficulty: "hard", options: ["2","3","4","6"], answer: "3", explanation: "x=√(6+x). x²-x-6=0. (x-3)(x+2)=0. x=3." },
  { title: "MP-H-19 Bells Three Intervals", description: "Three bells ring at intervals of 9, 12, 15 minutes. All ring together at 10AM. Next time all ring together?", topic: "Math Puzzles", difficulty: "hard", options: ["11:00 AM","12:00 PM","1:00 PM","11:30 AM"], answer: "1:00 PM", explanation: "LCM(9,12,15)=180 minutes=3 hours. 10AM+3h=1PM." },
  { title: "MP-H-20 Expected Value Dice", description: "Roll die: Win ₹30 if even, lose ₹15 if odd. Expected value per game?", topic: "Math Puzzles", difficulty: "hard", options: ["₹7.50","₹5","₹2.50","₹0"], answer: "₹7.50", explanation: "E=30×0.5+(-15)×0.5=15-7.5=₹7.50." },
  { title: "MP-H-21 Partial Fractions A", description: "Resolve 1/((x-1)(x+2)) into A/(x-1)+B/(x+2). Find A.", topic: "Math Puzzles", difficulty: "hard", options: ["1/3","1/2","1/4","2/3"], answer: "1/3", explanation: "At x=1: 1=A×3. A=1/3." },
  { title: "MP-H-22 Sphere Cylinder Volume Ratio", description: "Cylinder circumscribes sphere of radius r. Ratio of volumes cylinder:sphere?", topic: "Math Puzzles", difficulty: "hard", options: ["3:2","2:3","3:1","1:3"], answer: "3:2", explanation: "V(cylinder)=πr²×2r=2πr³. V(sphere)=4πr³/3. Ratio=2÷(4/3)=3/2." },
  { title: "MP-H-23 Trig Identity Sin Cos", description: "If sin(A)+sin²(A)=1, find cos²(A)+cos⁴(A).", topic: "Math Puzzles", difficulty: "hard", options: ["0","1","2","3"], answer: "1", explanation: "sin(A)=cos²(A). cos²(A)+cos⁴(A)=sin(A)+sin²(A)=1." },
  { title: "MP-H-24 Collatz 27 Steps", description: "Collatz sequence starting from 27. How many steps to reach 1?", topic: "Math Puzzles", difficulty: "hard", options: ["96","100","111","123"], answer: "111", explanation: "27 takes exactly 111 steps to reach 1 in the Collatz sequence, reaching max 9232." },
  { title: "MP-H-25 Probability Cards Kings Queens", description: "Two cards drawn from standard deck of 52. P(both kings OR both queens)?", topic: "Math Puzzles", difficulty: "hard", options: ["2/221","1/110","3/221","4/221"], answer: "2/221", explanation: "P(both kings)=6/1326. P(both queens)=6/1326. Total=12/1326=2/221." },

  // ── VERBAL REASONING · EASY (20) ──────────────────────────────
  { title: "VR-E-01 Civic Equality Meaning", description: "French Revolution replaced inherited status with civic equality. What does 'civic equality' imply?", topic: "Verbal Reasoning", difficulty: "easy", options: ["All citizens same income","Equal rights before law regardless of birth","Everyone performs same duties","Nobility replaced by meritocracy"], answer: "Equal rights before law regardless of birth", explanation: "Civic equality means legal equality before the law regardless of noble birth." },
  { title: "VR-E-02 Committee Singular", description: "Identify grammatically correct sentence:", topic: "Verbal Reasoning", difficulty: "easy", options: ["The committee have reached their decision unanimously.","The committee has reached its decision unanimously.","The committee has reached their decision unanimously.","The committees has reached its decision unanimously."], answer: "The committee has reached its decision unanimously.", explanation: "Collective nouns like 'committee' take singular verbs and pronouns: has, its." },
  { title: "VR-E-03 Antonym Truculent", description: "Antonym of TRUCULENT:", topic: "Verbal Reasoning", difficulty: "easy", options: ["Bellicose","Placid","Aggressive","Pugnacious"], answer: "Placid", explanation: "Truculent=aggressively defiant. Antonym=Placid (calm, peaceful)." },
  { title: "VR-E-04 Para Jumble India GDP", description: "Arrange: (A)Economic growth without equity causes unrest (B)India has remarkable GDP growth (C)Inclusive growth is paramount policy objective (D)Growth not uniformly distributed.", topic: "Verbal Reasoning", difficulty: "easy", options: ["BDAC","BDCA","BADC","ABDC"], answer: "BDAC", explanation: "B(topic)→D(limitation)→A(consequence)→C(conclusion). BDAC." },
  { title: "VR-E-05 Probity Synonym", description: "In governance, PROBITY most closely means:", topic: "Verbal Reasoning", difficulty: "easy", options: ["Severity","Probability","Integrity","Inquiry"], answer: "Integrity", explanation: "Probity means complete honesty and strong moral uprightness." },
  { title: "VR-E-06 Stoic Definition", description: "Person indifferent to pleasure or pain who accepts whatever happens:", topic: "Verbal Reasoning", difficulty: "easy", options: ["Epicurean","Stoic","Cynic","Ascetic"], answer: "Stoic", explanation: "Stoic endures pain or hardship without complaint." },
  { title: "VR-E-07 Number of Accidents", description: "Error: 'The number of accidents have increased drastically this year.'", topic: "Verbal Reasoning", difficulty: "easy", options: ["Change have to has","Change increased to increasing","Change drastically to drastic","No error"], answer: "Change have to has", explanation: "'The number of' takes singular verb: 'has increased.'" },
  { title: "VR-E-08 Ubiquitous Meaning", description: "UBIQUITOUS most nearly means:", topic: "Verbal Reasoning", difficulty: "easy", options: ["Rare","Present everywhere","Unique","Dangerous"], answer: "Present everywhere", explanation: "Ubiquitous from Latin 'ubique'=everywhere." },
  { title: "VR-E-09 Epistemology Analogy", description: "Jurisprudence : Law :: Epistemology : ?", topic: "Verbal Reasoning", difficulty: "easy", options: ["Ethics","Knowledge","Language","Society"], answer: "Knowledge", explanation: "Jurisprudence=philosophy of law. Epistemology=philosophy of knowledge." },
  { title: "VR-E-10 Sarcasm Detection", description: "Passage: 'Once again government graciously consults people it governs — week before election.' Author's tone?", topic: "Verbal Reasoning", difficulty: "easy", options: ["Appreciative","Sarcastic","Neutral","Melancholic"], answer: "Sarcastic", explanation: "'Graciously' used for token pre-election consultation reveals sarcasm." },
  { title: "VR-E-11 Cloze Democratic Institutions", description: "The _____ of democratic institutions requires citizenry that actively _____ in governance.", topic: "Verbal Reasoning", difficulty: "easy", options: ["sustenance / participates","destruction / engages","sustenance / abstains","reinforcement / avoids"], answer: "sustenance / participates", explanation: "Sustenance of institutions requires active participation — logically consistent." },
  { title: "VR-E-12 Passive Voice Supreme Court", description: "Change to passive: 'The Supreme Court has delivered a landmark judgment.'", topic: "Verbal Reasoning", difficulty: "easy", options: ["A landmark judgment was being delivered by the Supreme Court.","A landmark judgment has been delivered by the Supreme Court.","A landmark judgment is delivered by the Supreme Court.","A landmark judgment had been delivered by the Supreme Court."], answer: "A landmark judgment has been delivered by the Supreme Court.", explanation: "Present perfect passive: has been delivered." },
  { title: "VR-E-13 Subjunctive Were", description: "Which sentence correctly uses the subjunctive mood?", topic: "Verbal Reasoning", difficulty: "easy", options: ["If I was you I would apologize.","The committee insisted that he resigns.","If I were you I would apologize.","She demanded that he will leave."], answer: "If I were you I would apologize.", explanation: "Subjunctive uses 'were' for hypothetical conditions." },
  { title: "VR-E-14 Living Dead Oxymoron", description: "Which phrase is an oxymoron?", topic: "Verbal Reasoning", difficulty: "easy", options: ["Dark night","Living dead","Heavy rain","Deep water"], answer: "Living dead", explanation: "Oxymoron combines contradictory terms. Living dead juxtaposes mutually exclusive states." },
  { title: "VR-E-15 Laffer Curve", description: "The Laffer Curve illustrates relationship between:", topic: "Verbal Reasoning", difficulty: "easy", options: ["Inflation and unemployment","Tax rates and tax revenue collected","Investment and interest rates","Trade deficit and currency value"], answer: "Tax rates and tax revenue collected", explanation: "Laffer Curve: both 0% and 100% tax rates generate zero revenue, maximum at some intermediate rate." },
  { title: "VR-E-16 Enervate Correct Usage", description: "Which sentence uses ENERVATE correctly?", topic: "Verbal Reasoning", difficulty: "easy", options: ["Coffee enervated her before exam.","Humidity enervated the players by halftime.","His speech enervated the crowd.","Medicine enervated her positively."], answer: "Humidity enervated the players by halftime.", explanation: "Enervate=weaken or drain of energy. Humidity draining energy is correct." },
  { title: "VR-E-17 Parallel Structure Swimming", description: "Choose sentence with correct parallel structure:", topic: "Verbal Reasoning", difficulty: "easy", options: ["She likes to swim running and to cycle.","She likes swimming to run and cycling.","She likes swimming running and cycling.","She likes to swim to running and cycle."], answer: "She likes swimming running and cycling.", explanation: "Swimming, running, cycling — all gerunds. Correctly parallel." },
  { title: "VR-E-18 Scrawny Negative Connotation", description: "Which word carries most negative connotation among: slim, slender, scrawny, svelte?", topic: "Verbal Reasoning", difficulty: "easy", options: ["Slim","Slender","Scrawny","Svelte"], answer: "Scrawny", explanation: "Scrawny implies unattractively thin, suggesting weakness. Svelte is positive." },
  { title: "VR-E-19 Spelling Accommodation", description: "Which is spelled correctly?", topic: "Verbal Reasoning", difficulty: "easy", options: ["Accomodation","Accommodation","Acommodation","Acomodation"], answer: "Accommodation", explanation: "Double 'c' and double 'm'. Accommodation." },
  { title: "VR-E-20 Demographic Dividend", description: "Demographic dividend refers to:", topic: "Verbal Reasoning", difficulty: "easy", options: ["Financial benefits of fewer children","Economic growth potential from large working-age population relative to dependents","Government payments to families","Tax benefits for demographic surveys"], answer: "Economic growth potential from large working-age population relative to dependents", explanation: "When working-age population is large relative to dependents — potential for accelerated economic growth." },

  // ── VERBAL REASONING · MEDIUM (20) ────────────────────────────
  { title: "VR-M-01 Tragedy of Commons", description: "Hardin: tragedy of commons occurs when self-interest depletes shared resources. Ostrom: communities develop governance mechanisms without privatization or state control. Main point?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Hardin's theory is correct","Only privatization solves commons","Empirical evidence challenges Hardin showing community self-governance works","State control is necessary"], answer: "Empirical evidence challenges Hardin showing community self-governance works", explanation: "Ostrom's empirical counter-evidence challenges Hardin's pessimistic theory." },
  { title: "VR-M-02 Austerity Contradiction", description: "All countries using fiscal austerity 2010-2015 had slower growth. Finance Minister recommends austerity to grow economy. Flaw?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Ad hominem","Recommendation contradicts stated evidence","Austerity is always bad","Growth is not only indicator"], answer: "Recommendation contradicts stated evidence", explanation: "Evidence shows austerity slows growth yet minister recommends it for growth — direct logical contradiction." },
  { title: "VR-M-03 Anthropocene Para Jumble", description: "Arrange P(Anthropocene marks epoch) R(Human activity transformed systems) Q(Mastery destabilized planetary boundaries) S(Defining question of century).", topic: "Verbal Reasoning", difficulty: "medium", options: ["PRQS","PRSQ","QPRS","RPSQ"], answer: "PRQS", explanation: "P(define)→R(examples)→Q(cost-contrast with yet)→S(conclusion). PRQS." },
  { title: "VR-M-04 Music Math Causation", description: "Students taking music lessons score higher in math. Conclusion: Music training improves math. Assumption being made?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Music and math use different brain regions","Correlation represents causation not a third common factor","All music students are gifted","Both are equally important"], answer: "Correlation represents causation not a third common factor", explanation: "Assumes no confounding variable like family affluence independently causing both." },
  { title: "VR-M-05 Governor Equivocation", description: "Governor's speech was masterpiece of _______, making promises that committed to nothing while appearing to commit to everything.", topic: "Verbal Reasoning", difficulty: "medium", options: ["equivocation","candor","probity","perspicacity"], answer: "equivocation", explanation: "Equivocation=using ambiguous language to conceal truth or avoid commitment." },
  { title: "VR-M-06 Treaty Binding Unenforceable", description: "The treaty's provisions, though _____ in letter, were _____ in practice, creating obligations that signatories systematically circumvented.", topic: "Verbal Reasoning", difficulty: "medium", options: ["binding / unenforceable","vague / strict","optional / mandatory","flexible / rigid"], answer: "binding / unenforceable", explanation: "Binding in letter but unenforceable in practice creates the described contrast." },
  { title: "VR-M-07 Toothpaste Ad Assumption", description: "Ad: Nine out of ten dentists recommend Sparkle toothpaste. The implicit assumption is:", topic: "Verbal Reasoning", difficulty: "medium", options: ["Sparkle is the best available","Dentists recommendations reliably guide consumer dental health choices","The tenth dentist is wrong","All toothpastes are equally effective"], answer: "Dentists recommendations reliably guide consumer dental health choices", explanation: "The ad's persuasive power rests entirely on this assumption." },
  { title: "VR-M-08 Anomie Sociology", description: "Entropy : Thermodynamics :: Anomie : ?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Physics","Chemistry","Sociology","Psychology"], answer: "Sociology", explanation: "Entropy central to thermodynamics. Anomie (Durkheim's social normlessness) central to sociology." },
  { title: "VR-M-09 Error Spotting Three Errors", description: "Error in: 'Being that he was the senior most officer, the responsibility of command laid with him.'", topic: "Verbal Reasoning", difficulty: "medium", options: ["Being that should be Since/Because","senior most should be most senior","laid should be lay","All of the above"], answer: "All of the above", explanation: "'Being that' non-standard; 'Most senior' correct order; 'lay' not 'laid' for intransitive." },
  { title: "VR-M-10 Valid Not Sound", description: "Philosopher: Free will incompatible with determinism. Determinism true. Therefore free will is illusion. This is:", topic: "Verbal Reasoning", difficulty: "medium", options: ["Valid with true premises","Valid but conclusion may be rejected by rejecting premise","Invalid argument","Sound argument"], answer: "Valid but conclusion may be rejected by rejecting premise", explanation: "Logically valid but not necessarily sound — one can reject determinism." },
  { title: "VR-M-11 Liberalization Balance", description: "Author: Economic liberalization created unprecedented wealth but also unprecedented inequality. Author's stance?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Strongly pro-liberalization","Strongly anti-liberalization","Balanced and nuanced","Politically evasive"], answer: "Balanced and nuanced", explanation: "Acknowledges both positive and negative outcomes without advocating a position." },
  { title: "VR-M-12 Watchmaker Analogy", description: "'Just as clock has clockmaker, universe must have designer.' This argument uses:", topic: "Verbal Reasoning", difficulty: "medium", options: ["Valid deductive reasoning","Argument by analogy whose strength depends on similarity between clock and universe","Ad hominem","Circular reasoning"], answer: "Argument by analogy whose strength depends on similarity between clock and universe", explanation: "Paley's Watchmaker argument — force depends on how similar universe is to a clock." },
  { title: "VR-M-13 Welfare State Paradox", description: "Welfare state faces existential questioning — not because it failed but because it succeeded. What does this mean?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Welfare state is being dismantled","Success raised expectations and fiscal pressures challenging sustainability","Social democracy is obsolete","Welfare states fail in capitalist countries"], answer: "Success raised expectations and fiscal pressures challenging sustainability", explanation: "Success — longer lives, reduced poverty — created larger dependent populations straining fiscal foundations." },
  { title: "VR-M-14 TV Life Expectancy", description: "Countries with more TVs have higher life expectancy. Columnist: Buying TVs extends life. Error?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Selection bias","Confusing correlation with causation — both reflect underlying wealth","Hasty generalization","False dichotomy"], answer: "Confusing correlation with causation — both reflect underlying wealth", explanation: "National wealth independently causes both TV ownership and better healthcare — spurious correlation." },
  { title: "VR-M-15 Article 356 Constitution", description: "Article 356 of Indian Constitution (President's Rule) can be imposed when:", topic: "Verbal Reasoning", difficulty: "medium", options: ["State government requests central aid","Constitutional machinery in a state has failed","State passes unconstitutional law","State Chief Minister resigns"], answer: "Constitutional machinery in a state has failed", explanation: "Article 356: when government of state cannot be carried on in accordance with Constitutional provisions." },
  { title: "VR-M-16 Studied Vagueness", description: "'Commission's report was a masterwork of STUDIED vagueness.' STUDIED here means:", topic: "Verbal Reasoning", difficulty: "medium", options: ["Academic","Deliberate and intentional","Researched thoroughly","Confused"], answer: "Deliberate and intentional", explanation: "Studied=carefully contrived and deliberate. The vagueness was intentional." },
  { title: "VR-M-17 Voting Citizens Logic", description: "Only citizens can vote. Ram voted. Therefore Ram is a citizen. This reasoning commits:", topic: "Verbal Reasoning", difficulty: "medium", options: ["No fallacy","Affirming the consequent","Denying the antecedent","Circular reasoning"], answer: "Affirming the consequent", explanation: "P→Q, Q, therefore P. Affirming the consequent — invalid inference." },
  { title: "VR-M-18 Sardonic Minister", description: "Passage: 'The minister displaying customary grasp of economic reality proposed cutting education funding as though education were luxury.' Tone?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Neutral","Appreciative","Sardonic and bitterly ironic","Melancholic"], answer: "Sardonic and bitterly ironic", explanation: "'Customary grasp' implying he lacks it reveals sardonic irony." },
  { title: "VR-M-19 Perspicuity Ambiguity", description: "The _____ of the court's judgment left little room for _____ — its meaning was unmistakably clear.", topic: "Verbal Reasoning", difficulty: "medium", options: ["perspicuity / ambiguity","opacity / clarity","prolixity / brevity","equivocation / directness"], answer: "perspicuity / ambiguity", explanation: "Perspicuity=clearness of expression. Clear judgment leaves no room for ambiguity." },
  { title: "VR-M-20 Induction Empiricism", description: "Induction : Empiricism :: Deduction : ?", topic: "Verbal Reasoning", difficulty: "medium", options: ["Rationalism","Skepticism","Pragmatism","Relativism"], answer: "Rationalism", explanation: "Induction is primary method of Empiricism. Deduction is primary method of Rationalism." },

  // ── VERBAL REASONING · HARD (12) ──────────────────────────────
  { title: "VR-H-01 Market Efficiency Critique", description: "Passage: Market efficiency defined as producing what consumers demand at least cost — makes no judgment whether demand reflects genuine human flourishing or manufactured desire. Author implicitly critiques?", topic: "Verbal Reasoning", difficulty: "hard", options: ["Markets are inefficient","Definition of market efficiency is value-neutral in way that obscures normative questions","Consumer demand should be regulated","Human flourishing and efficiency are identical"], answer: "Definition of market efficiency is value-neutral in way that obscures normative questions", explanation: "Author critiques that 'efficiency' as defined sidesteps what should be produced — a normative question." },
  { title: "VR-H-02 Churchill Anaphora", description: "Churchill: 'We shall fight on the beaches, we shall fight on the landing grounds...' Primary rhetorical device?", topic: "Verbal Reasoning", difficulty: "hard", options: ["Metaphor creates imagery","Anaphora creates rhythmic emphasis and psychological resolve through repetition","Alliteration creates sonic impact","Hyperbole exaggerates for effect"], answer: "Anaphora creates rhythmic emphasis and psychological resolve through repetition", explanation: "Anaphora: repetition at beginning of successive clauses creates cumulative momentum." },
  { title: "VR-H-03 Liar Paradox Self Reference", description: "The sentence 'This statement is false' is an example of:", topic: "Verbal Reasoning", difficulty: "hard", options: ["A false statement","An ambiguous statement","The Liar Paradox — self-referential statement with no consistent truth value","A meaningless statement"], answer: "The Liar Paradox — self-referential statement with no consistent truth value", explanation: "If true it must be false; if false it must be true. Classic self-referential paradox." },
  { title: "VR-H-04 UBI Consequentialist", description: "Economist A: Implement UBI because automation will cause structural unemployment. Economist B: UBI has never worked at national scale. A's argument type and B's response?", topic: "Verbal Reasoning", difficulty: "hard", options: ["A consequentialist B challenges empirical premise","A deontological B consequentialist counter","A empirical B refutes with principle","Both same type"], answer: "A consequentialist B challenges empirical premise", explanation: "A argues based on consequences. B challenges empirical track record of the policy." },
  { title: "VR-H-05 Sanguine Definition", description: "SANGUINE most closely means?", topic: "Verbal Reasoning", difficulty: "hard", options: ["Pessimistic","Optimistic","Aggressive","Passive"], answer: "Optimistic", explanation: "Sanguine=optimistic, especially in difficult situations." },
  { title: "VR-H-06 Telescope Two Interpretations", description: "'She saw the man with the telescope.' How many interpretations?", topic: "Verbal Reasoning", difficulty: "hard", options: ["1","2","3","4"], answer: "2", explanation: "She used telescope to see man, OR man had a telescope. Two valid interpretations." },
  { title: "VR-H-07 Philosophy Etymology", description: "Word PHILOSOPHY comes from Greek PHILO+SOPHIA meaning?", topic: "Verbal Reasoning", difficulty: "hard", options: ["Love of wisdom","Study of nature","Art of speaking","Science of numbers"], answer: "Love of wisdom", explanation: "Philo=love, Sophia=wisdom. Philosophy=love of wisdom." },
  { title: "VR-H-08 Chiasmus JFK", description: "JFK: 'Ask not what your country can do for you — ask what you can do for your country.' This device is:", topic: "Verbal Reasoning", difficulty: "hard", options: ["Anaphora","Epistrophe","Chiasmus","Asyndeton"], answer: "Chiasmus", explanation: "Chiasmus reverses grammatical structures of two clauses — ABBA pattern." },
  { title: "VR-H-09 Textual Coherence Federalism", description: "S1: Federalism divides sovereignty. S2: States retain powers not delegated. [INSERT] S3: This tension defined Indian constitutional interpretation since 1950. Best insert?", topic: "Verbal Reasoning", difficulty: "hard", options: ["India is a large country with diverse regions.","Yet this division inevitably creates friction when central and state jurisdictions overlap.","The Supreme Court has many judges.","Citizens benefit from decentralized governance."], answer: "Yet this division inevitably creates friction when central and state jurisdictions overlap.", explanation: "Bridges S2 (retained state powers) and S3 (tension defines interpretation)." },
  { title: "VR-H-10 Diversity Training Weakens", description: "Claim: Companies with diverse boards outperform others therefore diversity training improves performance. Which weakens most?", topic: "Verbal Reasoning", difficulty: "hard", options: ["Diverse boards have more experience","Diversity training rarely leads to truly diverse boards","Performance metrics vary by industry","Some diverse companies perform poorly"], answer: "Diversity training rarely leads to truly diverse boards", explanation: "If training doesn't produce diverse boards, the entire causal chain breaks." },
  { title: "VR-H-11 Gettier JTB", description: "Smith has justified true belief that man with 10 coins gets job. Smith gets job and also has 10 coins. Does Smith KNOW?", topic: "Verbal Reasoning", difficulty: "hard", options: ["Yes — justified true belief equals knowledge","No — true by accident not because of justification","Yes — the belief is true","Cannot determine"], answer: "No — true by accident not because of justification", explanation: "Gettier's counterexample: JTB insufficient for knowledge. Truth is accidental." },
  { title: "VR-H-12 Godel Incompleteness", description: "Gödel's First Incompleteness Theorem states any consistent formal system strong enough to express arithmetic:", topic: "Verbal Reasoning", difficulty: "hard", options: ["Contains contradictions","Is complete and consistent","Contains true statements that cannot be proved within the system","Cannot express addition"], answer: "Contains true statements that cannot be proved within the system", explanation: "Gödel: there exist true but unprovable statements in any consistent system expressing arithmetic." },

  // ── PATTERN RECOGNITION · EASY (20) ───────────────────────────
  { title: "PR-E-01 Fibonacci Next", description: "1, 1, 2, 3, 5, 8, 13, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["18","19","20","21"], answer: "21", explanation: "8+13=21. Fibonacci sequence." },
  { title: "PR-E-02 Matrix Cubes", description: "3×3 matrix rows: [2,4,8], [3,9,27], [4,16,?]. Find ?", topic: "Pattern Recognition", difficulty: "easy", options: ["32","48","64","36"], answer: "64", explanation: "Each row: x, x², x³. Row 3: 4,16,64." },
  { title: "PR-E-03 Doubling Series", description: "3, 6, 12, 24, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["36","42","48","54"], answer: "48", explanation: "×2 each time. 24×2=48." },
  { title: "PR-E-04 Adding Five Series", description: "5, 10, 15, 20, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["22","24","25","30"], answer: "25", explanation: "+5 each time. 20+5=25." },
  { title: "PR-E-05 Diamond Circle Pattern", description: "◆◆○◆◆○◆◆?", topic: "Pattern Recognition", difficulty: "easy", options: ["○","◆","□","△"], answer: "○", explanation: "Pattern ◆◆○ repeats. After ◆◆ comes ○." },
  { title: "PR-E-06 Halving Powers", description: "256, 128, 64, 32, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["8","12","16","20"], answer: "16", explanation: "÷2 each time. 32÷2=16." },
  { title: "PR-E-07 Perfect Squares Series", description: "1, 4, 9, 16, 25, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["30","35","36","40"], answer: "36", explanation: "1²,2²,3²,4²,5²,6²=36." },
  { title: "PR-E-08 Cube Numbers Series", description: "1, 8, 27, 64, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["100","115","125","135"], answer: "125", explanation: "1³,2³,3³,4³,5³=125." },
  { title: "PR-E-09 Letter Skip Three", description: "B, E, H, K, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["M","N","O","L"], answer: "N", explanation: "+3 each time. B(2),E(5),H(8),K(11),N(14)." },
  { title: "PR-E-10 Subtract Six Series", description: "50, 44, 38, 32, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["24","26","28","30"], answer: "26", explanation: "-6 each time. 32-6=26." },
  { title: "PR-E-11 Letter Number Mix AB", description: "AB1, CD4, EF9, GH16, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["IJ25","IK25","IJ20","HI25"], answer: "IJ25", explanation: "Letters +2 each group, numbers are squares: 1,4,9,16,25. IJ25." },
  { title: "PR-E-12 Number Analogy Square", description: "16:256 :: 17:?", topic: "Pattern Recognition", difficulty: "easy", options: ["289","296","302","284"], answer: "289", explanation: "16:16²=256. 17:17²=289." },
  { title: "PR-E-13 Magic Constant Formula", description: "In any n×n magic square, magic constant=n(n²+1)/2. For n=5, constant=?", topic: "Pattern Recognition", difficulty: "easy", options: ["55","65","75","85"], answer: "65", explanation: "5(25+1)/2=65." },
  { title: "PR-E-14 Color Repeat Pattern", description: "Red, Blue, Green, Red, Blue, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["Red","Blue","Green","Yellow"], answer: "Green", explanation: "Pattern Red,Blue,Green repeats." },
  { title: "PR-E-15 Word Length Increasing", description: "A, To, Cat, Door, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["Elephant","Table","Three","Chess"], answer: "Three", explanation: "Words 1,2,3,4,5 letters. Five-letter word=Three." },
  { title: "PR-E-16 Triangular Numbers", description: "Series of circles with 1,3,6,10 dots. How many dots in 6th circle?", topic: "Pattern Recognition", difficulty: "easy", options: ["15","18","21","24"], answer: "21", explanation: "Triangular numbers n(n+1)/2. 6th: 6×7/2=21." },
  { title: "PR-E-17 Min Cuts 64 Cubes", description: "Minimum cuts to cut a cube into 64 equal smaller cubes?", topic: "Pattern Recognition", difficulty: "easy", options: ["9","10","12","8"], answer: "9", explanation: "64=4³. Each dimension needs 3 cuts. 3×3=9 total." },
  { title: "PR-E-18 Symmetry Palindrome", description: "ABCBA, ABCDCBA, ABCDEDCBA, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["ABCDEFEDCBA","ABCDEFGFEDCBA","ABCDEEEDCBA","ABCDFEDCBA"], answer: "ABCDEFEDCBA", explanation: "Each pattern adds one more middle letter. Next adds F: ABCDEFEDCBA." },
  { title: "PR-E-19 Alphanumeric BFJNR", description: "BFJNR:2,6,10,14,18 :: CGKOS:?", topic: "Pattern Recognition", difficulty: "easy", options: ["3,7,11,15,19","3,7,11,14,19","3,6,11,15,19","4,7,11,15,19"], answer: "3,7,11,15,19", explanation: "C=3,G=7,K=11,O=15,S=19. Same +4 pattern starting from 3." },
  { title: "PR-E-20 Series Double Minus One", description: "3, 5, 9, 17, 33, ?", topic: "Pattern Recognition", difficulty: "easy", options: ["55","63","65","67"], answer: "65", explanation: "Each term = 2×previous - 1. 33×2-1=65." },

  // ── PATTERN RECOGNITION · MEDIUM (20) ─────────────────────────
  { title: "PR-M-01 Differences Increasing", description: "Find next: 2, 6, 12, 20, 30, 42, ?", topic: "Pattern Recognition", difficulty: "medium", options: ["52","54","56","58"], answer: "56", explanation: "Differences: 4,6,8,10,12,14. Next=42+14=56." },
  { title: "PR-M-02 Series n squared plus n", description: "If 2+3=13, 4+5=41, 6+7=85, then 8+9=?", topic: "Pattern Recognition", difficulty: "medium", options: ["145","153","161","169"], answer: "145", explanation: "Pattern: a²+b². 8²+9²=64+81=145." },
  { title: "PR-M-03 Word Letter Shift", description: "ACE, BDF, CEG, DFH, ?", topic: "Pattern Recognition", difficulty: "medium", options: ["EGI","EHI","FGI","EGH"], answer: "EGI", explanation: "Each group shifts +1 in all letters. EGI." },
  { title: "PR-M-04 Factorial Sequence", description: "1, 2, 6, 24, 120, 720, 5040, ?", topic: "Pattern Recognition", difficulty: "medium", options: ["35280","40320","40520","38240"], answer: "40320", explanation: "Factorials. 8!=40320." },
  { title: "PR-M-05 Reverse Alphabet Code", description: "If DESTABILIZE coded as WVHGZYBORAV, what pattern is used?", topic: "Pattern Recognition", difficulty: "medium", options: ["Mirror alphabet A=Z B=Y etc","ROT13","Reverse alphabet equivalent","Vowels only replaced"], answer: "Reverse alphabet equivalent", explanation: "D(4)→W(23). Position n maps to 27-n. Reverse alphabet." },
  { title: "PR-M-06 Grid Powers of N", description: "3×3 grid rows: [1,8,27],[64,125,216],[343,512,?]. Find ?", topic: "Pattern Recognition", difficulty: "medium", options: ["625","729","900","512"], answer: "729", explanation: "Cubes in order. 9³=729." },
  { title: "PR-M-07 Pascal Row Sum", description: "Sum of all elements in row 7 of Pascal's Triangle (Row 1=[1])?", topic: "Pattern Recognition", difficulty: "medium", options: ["32","64","128","256"], answer: "64", explanation: "Sum of row n=2^(n-1). Row 7: 2^6=64." },
  { title: "PR-M-08 Cryptarithmetic SEND MORE", description: "SEND+MORE=MONEY. S=9,E=5,N=6,D=7,M=1,O=0,R=8,Y=2. What is MONEY?", topic: "Pattern Recognition", difficulty: "medium", options: ["10652","10682","10562","10582"], answer: "10652", explanation: "M=1,O=0,N=6,E=5,Y=2. MONEY=10652. 9567+1085=10652 ✓" },
  { title: "PR-M-09 Mirror Number Three", description: "12321, 123321, 1233321, ?", topic: "Pattern Recognition", difficulty: "medium", options: ["12333321","12344321","123444321","1234321"], answer: "12333321", explanation: "One more 3 added in middle each time." },
  { title: "PR-M-10 Rotation Net Degrees", description: "Shape rotates 90° clockwise per step. After 7 steps, net rotation from start?", topic: "Pattern Recognition", difficulty: "medium", options: ["0°","90°","180°","270°"], answer: "270°", explanation: "7×90=630. 630 mod 360=270°." },
  { title: "PR-M-11 Alternating Signs", description: "1, -2, 3, -4, 5, -6, ?", topic: "Pattern Recognition", difficulty: "medium", options: ["6","7","-7","8"], answer: "7", explanation: "Alternating positive/negative integers. Next positive=7." },
  { title: "PR-M-12 Recaman Sequence", description: "Recaman: a(0)=0, a(n)=a(n-1)-n if positive and not yet in sequence, else a(n-1)+n. First 7 terms?", topic: "Pattern Recognition", difficulty: "medium", options: ["0,1,3,6,2,7,13","0,1,3,6,2,7,12","0,1,3,5,2,7,13","0,2,3,6,2,7,13"], answer: "0,1,3,6,2,7,13", explanation: "a(0)=0,a(1)=1,a(2)=3,a(3)=6,a(4)=2,a(5)=7,a(6)=13." },
  { title: "PR-M-13 Doomsday 2024 Christmas", description: "Doomsday 2024 is Thursday. 12/12 is Thursday. What day is 25 December 2024?", topic: "Pattern Recognition", difficulty: "medium", options: ["Tuesday","Wednesday","Thursday","Friday"], answer: "Wednesday", explanation: "12/12=Thursday. 25/12 is 13 days later. 13 mod 7=6. Thursday+6=Wednesday." },
  { title: "PR-M-14 Spiral Top Right Corner", description: "Numbers in spiral: center=1, ring 2 has 2-9 (8 numbers), ring 3 has 10-25 (16 numbers). Top-right corner of ring 3?", topic: "Pattern Recognition", difficulty: "medium", options: ["25","28","13","16"], answer: "25", explanation: "Top-right corner of ring n=(2n-1)². Ring 3: 5²=25." },
  { title: "PR-M-15 Hamming Distance XOR", description: "Hamming distance between binary strings 10101010 and 11001100?", topic: "Pattern Recognition", difficulty: "medium", options: ["2","4","6","8"], answer: "4", explanation: "XOR=01100110. Count 1s=4. Hamming distance=4." },
  { title: "PR-M-16 Koch Snowflake Sides", description: "Koch snowflake: Iteration 0=3 sides, Iteration 1=12, Iteration 2=48. Sides after iteration 4?", topic: "Pattern Recognition", difficulty: "medium", options: ["576","768","512","1024"], answer: "768", explanation: "Each iteration ×4. After 4: 3×4⁴=3×256=768." },
  { title: "PR-M-17 Calendar 2000 to 2010 Day", description: "Jan 1 2000 was Saturday. What day was Jan 1 2010?", topic: "Pattern Recognition", difficulty: "medium", options: ["Friday","Saturday","Sunday","Monday"], answer: "Friday", explanation: "10 years: 7 ordinary+3 leap. Odd days=7+6=13. 13 mod 7=6. Saturday+6=Friday." },
  { title: "PR-M-18 Compression Run Length", description: "Run-length encoding: AAAABBBCCCCCDDAA → 4A3B5C2D2A. Compression ratio (compressed/original)?", topic: "Pattern Recognition", difficulty: "medium", options: ["0.625","0.56","0.7","0.5"], answer: "0.625", explanation: "Original=16 chars, compressed=10 chars. Ratio=10/16=0.625." },
  { title: "PR-M-19 Padovan Sequence", description: "Padovan: P(0)=P(1)=P(2)=1, P(n)=P(n-2)+P(n-3). Find P(8).", topic: "Pattern Recognition", difficulty: "medium", options: ["5","7","9","11"], answer: "7", explanation: "P(3)=2,P(4)=2,P(5)=3,P(6)=4,P(7)=5,P(8)=P(6)+P(5)=4+3=7." },
  { title: "PR-M-20 Tribonacci Next", description: "0, 1, 1, 2, 4, 7, 13, 24, ?", topic: "Pattern Recognition", difficulty: "medium", options: ["41","44","46","48"], answer: "44", explanation: "Each term=sum of previous 3. 7+13+24=44." },

  // ── PATTERN RECOGNITION · HARD (20) ───────────────────────────
  { title: "PR-H-01 K7 Chromatic Number", description: "Complete graph K_7: how many edges and what is its chromatic number?", topic: "Pattern Recognition", difficulty: "hard", options: ["21 edges 7 colors","21 edges 6 colors","28 edges 7 colors","21 edges 4 colors"], answer: "21 edges 7 colors", explanation: "K_7 edges=7×6/2=21. Chromatic number=n=7." },
  { title: "PR-H-02 Wilson Theorem Twelve", description: "Wilson's theorem: (p-1)!≡-1(mod p) for prime p. What is 12! mod 13?", topic: "Pattern Recognition", difficulty: "hard", options: ["1","12","0","6"], answer: "12", explanation: "By Wilson: 12!≡-1≡12 (mod 13)." },
  { title: "PR-H-03 Look Say Three Twos", description: "After a run of three 2s in the look-and-say sequence, the next description is:", topic: "Pattern Recognition", difficulty: "hard", options: ["1","2","3,1","3,2"], answer: "3,2", explanation: "Look-and-say describes runs: three 2s → '32' (three twos)." },
  { title: "PR-H-04 Latin Square Five by Five", description: "5×5 Latin square. Row1:[1,2,3,4,5], Row2:[2,1,4,5,3], Row3:[3,4,5,1,2]. What is Row4 Column2?", topic: "Pattern Recognition", difficulty: "hard", options: ["3","4","5","Cannot determine"], answer: "5", explanation: "Column 2 has 2,1,4. Missing 3,5. Row 4 constraints → position 2=5 by elimination." },
  { title: "PR-H-05 DFA Binary Divisible", description: "Automaton accepts binary strings divisible by 3. Starting state q0. Process '110'. Accept?", topic: "Pattern Recognition", difficulty: "hard", options: ["Yes ends in q0","No ends in q1","No ends in q2","Yes ends in q2"], answer: "Yes ends in q0", explanation: "q0→1→q1→1→q0→0→q0. End q0. 110=6 divisible by 3. Accept." },
  { title: "PR-H-06 XOR Inverse Property", description: "Message 1010, key 1100. Encrypt XOR then encrypt ciphertext again with same key 1100. Result?", topic: "Pattern Recognition", difficulty: "hard", options: ["1010","0110","1100","0000"], answer: "1010", explanation: "XOR is its own inverse. M XOR K XOR K = M. Original recovered." },
  { title: "PR-H-07 Busy Beaver BB5", description: "Busy Beaver function: BB(1)=1,BB(2)=4,BB(3)=6,BB(4)=13. BB(5) was confirmed in 2024 to be:", topic: "Pattern Recognition", difficulty: "hard", options: ["47","4098","47176870","Uncomputable"], answer: "47176870", explanation: "BB(5)=47,176,870 confirmed in 2024. Grows faster than any computable function." },
  { title: "PR-H-08 Euler Formula Polyhedron", description: "Polyhedron has 20 vertices and 30 edges. V-E+F=2. How many faces?", topic: "Pattern Recognition", difficulty: "hard", options: ["10","12","14","16"], answer: "12", explanation: "20-30+F=2. F=12. Consistent with dodecahedron." },
  { title: "PR-H-09 Master Theorem Case Two", description: "T(n)=2T(n/2)+n·log n. By Master Theorem, complexity is:", topic: "Pattern Recognition", difficulty: "hard", options: ["O(n log n)","O(n log² n)","O(n² log n)","O(n²)"], answer: "O(n log² n)", explanation: "Extended case 2 of Master Theorem: T(n)=Θ(n log² n)." },
  { title: "PR-H-10 Quicksort Worst Case", description: "Which sorting algorithm has O(n log n) best, O(n log n) average, and O(n²) worst case?", topic: "Pattern Recognition", difficulty: "hard", options: ["Merge sort","Heap sort","Quick sort","Shell sort"], answer: "Quick sort", explanation: "Quicksort worst case O(n²) with poor pivot. Merge and Heap always O(n log n)." },
  { title: "PR-H-11 ACID Durability", description: "Property ensuring committed transaction remains so even after system failure:", topic: "Pattern Recognition", difficulty: "hard", options: ["Atomicity","Consistency","Isolation","Durability"], answer: "Durability", explanation: "ACID: Durability=committed transactions survive system failures." },
  { title: "PR-H-12 Cook Levin NP Complete", description: "SAT was first proven NP-Complete by:", topic: "Pattern Recognition", difficulty: "hard", options: ["Turing","Cook-Levin theorem","Dijkstra","Gödel"], answer: "Cook-Levin theorem", explanation: "Cook-Levin theorem (1971) proved SAT is NP-Complete — foundation of complexity theory." },
  { title: "PR-H-13 Prisoner Dilemma Nash", description: "Two firms: Both High:(10,10), Both Low:(4,4), A=High B=Low:(2,12), A=Low B=High:(12,2). Nash Equilibrium?", topic: "Pattern Recognition", difficulty: "hard", options: ["Both High","Both Low","A High B Low","A Low B High"], answer: "Both Low", explanation: "Prisoner's Dilemma. Low dominates for both. Nash Equilibrium: Both Low (4,4)." },
  { title: "PR-H-14 LCS Dynamic Programming", description: "Longest common subsequence of ABCBDAB and BDCAB has length:", topic: "Pattern Recognition", difficulty: "hard", options: ["3","4","5","6"], answer: "4", explanation: "LCS=BCAB or BDAB, length 4. Standard DP result." },
  { title: "PR-H-15 Bell Number B5", description: "Bell numbers: B(0)=1,B(1)=1,B(2)=2,B(3)=5,B(4)=15,B(5)=?", topic: "Pattern Recognition", difficulty: "hard", options: ["42","51","52","56"], answer: "52", explanation: "B(5)=52. Counts ways to partition 5-element set." },
  { title: "PR-H-16 Binary Necklace Burnside", description: "How many distinct binary necklaces with exactly 4 beads? (Rotations and reflections identical)", topic: "Pattern Recognition", difficulty: "hard", options: ["4","6","8","3"], answer: "6", explanation: "Burnside's lemma with dihedral group D4. Binary 4-bead necklaces: 6 distinct." },
  { title: "PR-H-17 Temporal Logic Always Eventually", description: "'Always eventually terminates' expressed in temporal logic as:", topic: "Pattern Recognition", difficulty: "hard", options: ["□◇terminated","◇□terminated","□terminated","◇terminated"], answer: "□◇terminated", explanation: "□◇P = at any point, eventually P. Correct formulation." },
  { title: "PR-H-18 Catalan C5", description: "Catalan number C(5) counts number of ways to fully parenthesize 6 numbers. C(5)=?", topic: "Pattern Recognition", difficulty: "hard", options: ["14","42","132","429"], answer: "42", explanation: "C(5)=C(10,5)/6=252/6=42." },
  { title: "PR-H-19 Hamiltonian K4", description: "Does K_4 have Hamiltonian cycles? How many distinct ones exist?", topic: "Pattern Recognition", difficulty: "hard", options: ["Yes and there are 3","Yes exactly one","No","Yes only with repeated edges"], answer: "Yes and there are 3", explanation: "(4-1)!/2=3!/2=3 distinct Hamiltonian cycles in K_4." },
  { title: "PR-H-20 Voronoi Vertices Max", description: "In Voronoi diagram with n seed points in general position, maximum number of Voronoi vertices (where 3 regions meet)?", topic: "Pattern Recognition", difficulty: "hard", options: ["n","2n-5","2n-3","n(n-1)/2"], answer: "2n-5", explanation: "By Euler's formula for planar graphs: maximum Voronoi vertices=2n-5 for n≥3." }
];

async function main() {
  console.log('Clearing existing data...');
  await prisma.progress.deleteMany();
  await prisma.problem.deleteMany();

  console.log(`Seeding ${problems.length} problems...`);

  const today = new Date();
  const data = problems.map((p, i) => {
    const podDate = new Date(today);
    podDate.setDate(today.getDate() + i);
    return {
      ...p,
      options: JSON.stringify(p.options),
      podDate,
    };
  });

  await prisma.problem.createMany({ data });

  const count = await prisma.problem.count();
  console.log(`\nSeeded ${count} problems successfully.`);

  const byTopic = {};
  const byDiff = {};
  problems.forEach(p => {
    byTopic[p.topic] = (byTopic[p.topic] || 0) + 1;
    byDiff[p.difficulty] = (byDiff[p.difficulty] || 0) + 1;
  });

  console.log('\nBy Topic:');
  Object.entries(byTopic).forEach(([t, c]) => console.log(`  ${t}: ${c}`));
  console.log('\nBy Difficulty:');
  Object.entries(byDiff).forEach(([d, c]) => console.log(`  ${d}: ${c}`));
}

main()
  .catch(e => { console.error('Seed failed:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());